# Generated by Django 3.2.8 on 2021-10-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('japanese_name', models.CharField(max_length=50)),
                ('generation', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(max_length=50)),
                ('height_m', models.FloatField()),
                ('weight_kg', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypeIntersections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against_bug', models.FloatField()),
                ('against_dark', models.FloatField()),
                ('against_dragon', models.FloatField()),
                ('against_electric', models.FloatField()),
                ('against_fairy', models.FloatField()),
                ('against_fight', models.FloatField()),
                ('against_fire', models.FloatField()),
                ('against_flying', models.FloatField()),
                ('against_ghost', models.FloatField()),
                ('against_grass', models.FloatField()),
                ('against_ground', models.FloatField()),
                ('against_ice', models.FloatField()),
                ('against_normal', models.FloatField()),
                ('against_poison', models.FloatField()),
                ('against_psychic', models.FloatField()),
                ('against_rock', models.FloatField()),
                ('against_steel', models.FloatField()),
                ('against_water', models.FloatField()),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_intersections', to='coreAPI.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('sp_attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('sp_defense', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('total_points', models.PositiveSmallIntegerField()),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='coreAPI.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonFurtherInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_rate', models.PositiveSmallIntegerField()),
                ('base_friendship', models.PositiveSmallIntegerField()),
                ('base_experience', models.PositiveSmallIntegerField()),
                ('growth_rate', models.CharField(max_length=50)),
                ('egg_type_1', models.CharField(max_length=20)),
                ('egg_type_2', models.CharField(max_length=20)),
                ('percentage_male', models.FloatField()),
                ('egg_cycles', models.PositiveSmallIntegerField()),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='coreAPI.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_1', models.CharField(max_length=50)),
                ('ability_2', models.CharField(max_length=50)),
                ('ability_hidden', models.CharField(max_length=50)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='coreAPI.pokemon')),
            ],
        ),
    ]
